package com.wool.acl.dao.mapper;

import com.wool.acl.model.database.UserGroupRelation;
import com.wool.acl.model.database.UserGroupRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserGroupRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wool_acl_user_group_relation
     *
     * @mbggenerated
     */
    int countByExample(UserGroupRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wool_acl_user_group_relation
     *
     * @mbggenerated
     */
    int deleteByExample(UserGroupRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wool_acl_user_group_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wool_acl_user_group_relation
     *
     * @mbggenerated
     */
    int insert(UserGroupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wool_acl_user_group_relation
     *
     * @mbggenerated
     */
    int insertSelective(UserGroupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wool_acl_user_group_relation
     *
     * @mbggenerated
     */
    List<UserGroupRelation> selectByExample(UserGroupRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wool_acl_user_group_relation
     *
     * @mbggenerated
     */
    UserGroupRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wool_acl_user_group_relation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserGroupRelation record, @Param("example") UserGroupRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wool_acl_user_group_relation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserGroupRelation record, @Param("example") UserGroupRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wool_acl_user_group_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserGroupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wool_acl_user_group_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserGroupRelation record);
}