package com.wool.acl.model.database;

public class Resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_resource.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_resource.app_id
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_resource.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_resource.resource_id
     *
     * @mbggenerated
     */
    private Integer resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_resource.resource_name
     *
     * @mbggenerated
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_resource.resouce_value
     *
     * @mbggenerated
     */
    private String resouceValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_resource.describe
     *
     * @mbggenerated
     */
    private String describe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_resource.id
     *
     * @return the value of wool_acl_resource.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_resource.id
     *
     * @param id the value for wool_acl_resource.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_resource.app_id
     *
     * @return the value of wool_acl_resource.app_id
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_resource.app_id
     *
     * @param appId the value for wool_acl_resource.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_resource.parent_id
     *
     * @return the value of wool_acl_resource.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_resource.parent_id
     *
     * @param parentId the value for wool_acl_resource.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_resource.resource_id
     *
     * @return the value of wool_acl_resource.resource_id
     *
     * @mbggenerated
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_resource.resource_id
     *
     * @param resourceId the value for wool_acl_resource.resource_id
     *
     * @mbggenerated
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_resource.resource_name
     *
     * @return the value of wool_acl_resource.resource_name
     *
     * @mbggenerated
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_resource.resource_name
     *
     * @param resourceName the value for wool_acl_resource.resource_name
     *
     * @mbggenerated
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_resource.resouce_value
     *
     * @return the value of wool_acl_resource.resouce_value
     *
     * @mbggenerated
     */
    public String getResouceValue() {
        return resouceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_resource.resouce_value
     *
     * @param resouceValue the value for wool_acl_resource.resouce_value
     *
     * @mbggenerated
     */
    public void setResouceValue(String resouceValue) {
        this.resouceValue = resouceValue == null ? null : resouceValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_resource.describe
     *
     * @return the value of wool_acl_resource.describe
     *
     * @mbggenerated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_resource.describe
     *
     * @param describe the value for wool_acl_resource.describe
     *
     * @mbggenerated
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }
}