package com.wool.acl.model.database;

public class RoleResourceRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_role_resource_relation.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_role_resource_relation.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_role_resource_relation.resource_id
     *
     * @mbggenerated
     */
    private Integer resourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_role_resource_relation.id
     *
     * @return the value of wool_acl_role_resource_relation.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_role_resource_relation.id
     *
     * @param id the value for wool_acl_role_resource_relation.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_role_resource_relation.role_id
     *
     * @return the value of wool_acl_role_resource_relation.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_role_resource_relation.role_id
     *
     * @param roleId the value for wool_acl_role_resource_relation.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_role_resource_relation.resource_id
     *
     * @return the value of wool_acl_role_resource_relation.resource_id
     *
     * @mbggenerated
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_role_resource_relation.resource_id
     *
     * @param resourceId the value for wool_acl_role_resource_relation.resource_id
     *
     * @mbggenerated
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }
}