package com.wool.acl.model.database;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_user.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_user.mail
     *
     * @mbggenerated
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_user.salt
     *
     * @mbggenerated
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_user.pw_dead_time
     *
     * @mbggenerated
     */
    private Integer pwDeadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_user.ctime
     *
     * @mbggenerated
     */
    private Integer ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_user.is_valid
     *
     * @mbggenerated
     */
    private Boolean isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_user.failure_times
     *
     * @mbggenerated
     */
    private Byte failureTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_user.failure_time
     *
     * @mbggenerated
     */
    private Integer failureTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_user.last_login_time
     *
     * @mbggenerated
     */
    private Integer lastLoginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_user.id
     *
     * @return the value of wool_acl_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_user.id
     *
     * @param id the value for wool_acl_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_user.login_name
     *
     * @return the value of wool_acl_user.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_user.login_name
     *
     * @param loginName the value for wool_acl_user.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_user.user_name
     *
     * @return the value of wool_acl_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_user.user_name
     *
     * @param userName the value for wool_acl_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_user.mail
     *
     * @return the value of wool_acl_user.mail
     *
     * @mbggenerated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_user.mail
     *
     * @param mail the value for wool_acl_user.mail
     *
     * @mbggenerated
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_user.phone
     *
     * @return the value of wool_acl_user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_user.phone
     *
     * @param phone the value for wool_acl_user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_user.salt
     *
     * @return the value of wool_acl_user.salt
     *
     * @mbggenerated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_user.salt
     *
     * @param salt the value for wool_acl_user.salt
     *
     * @mbggenerated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_user.password
     *
     * @return the value of wool_acl_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_user.password
     *
     * @param password the value for wool_acl_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_user.pw_dead_time
     *
     * @return the value of wool_acl_user.pw_dead_time
     *
     * @mbggenerated
     */
    public Integer getPwDeadTime() {
        return pwDeadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_user.pw_dead_time
     *
     * @param pwDeadTime the value for wool_acl_user.pw_dead_time
     *
     * @mbggenerated
     */
    public void setPwDeadTime(Integer pwDeadTime) {
        this.pwDeadTime = pwDeadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_user.ctime
     *
     * @return the value of wool_acl_user.ctime
     *
     * @mbggenerated
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_user.ctime
     *
     * @param ctime the value for wool_acl_user.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_user.is_valid
     *
     * @return the value of wool_acl_user.is_valid
     *
     * @mbggenerated
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_user.is_valid
     *
     * @param isValid the value for wool_acl_user.is_valid
     *
     * @mbggenerated
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_user.failure_times
     *
     * @return the value of wool_acl_user.failure_times
     *
     * @mbggenerated
     */
    public Byte getFailureTimes() {
        return failureTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_user.failure_times
     *
     * @param failureTimes the value for wool_acl_user.failure_times
     *
     * @mbggenerated
     */
    public void setFailureTimes(Byte failureTimes) {
        this.failureTimes = failureTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_user.failure_time
     *
     * @return the value of wool_acl_user.failure_time
     *
     * @mbggenerated
     */
    public Integer getFailureTime() {
        return failureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_user.failure_time
     *
     * @param failureTime the value for wool_acl_user.failure_time
     *
     * @mbggenerated
     */
    public void setFailureTime(Integer failureTime) {
        this.failureTime = failureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_user.last_login_time
     *
     * @return the value of wool_acl_user.last_login_time
     *
     * @mbggenerated
     */
    public Integer getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_user.last_login_time
     *
     * @param lastLoginTime the value for wool_acl_user.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Integer lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }
}