package com.wool.acl.model.database;

public class UserAppRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_user_app_relation.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_user_app_relation.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wool_acl_user_app_relation.app_id
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_user_app_relation.id
     *
     * @return the value of wool_acl_user_app_relation.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_user_app_relation.id
     *
     * @param id the value for wool_acl_user_app_relation.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_user_app_relation.uid
     *
     * @return the value of wool_acl_user_app_relation.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_user_app_relation.uid
     *
     * @param uid the value for wool_acl_user_app_relation.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wool_acl_user_app_relation.app_id
     *
     * @return the value of wool_acl_user_app_relation.app_id
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wool_acl_user_app_relation.app_id
     *
     * @param appId the value for wool_acl_user_app_relation.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }
}